src/volunteerz/hours/urls.py
from django.conf.urls import url


from .views import (
     HoursListView, 
    HoursDetailView, 
    HoursLocationCreateView
    )


urlpatterns = [
    url(r'^$', HoursListView.as_view(),name='list'),
   # url(r'^create2/$', HoursCreateView),
    url(r'^create/$', HoursLocationCreateView.as_view(),name='create'),
    url(r'^(?P<slug>[\w-]+)/$', HoursDetailView.as_view(),name='detail'),
]

src/volunteerz/volunteerz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from hours.views import (
     HoursListView, 
    HoursDetailView, 
    HoursLocationCreateView
    )


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^$', TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^hours', include('hours.urls' , namespace='hours')),
    url(r'^about/', TemplateView.as_view(template_name ='about.html'),name='about'),
    # url(r'^contact/', TemplateView.as_view(template_name='contact.html')),
]

src/volunteerz/hours/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.conf import settings
from django.core.urlresolvers import reverse


# Create your models here.
User = settings.AUTH_USER_MODEL

class HoursLocation(models.Model):
	owner				= models.ForeignKey(User)
	OpportunityNumber   = models.CharField(max_length =120)
	ChildsName         	= models.CharField(max_length =120)
	location     		= models.CharField(max_length =120, null=True, blank =True)
	hours        		= models.CharField(max_length =120, null = True, blank = True)
	timestamp    		= models.DateTimeField(auto_now_add =True)
	updated	     		= models.DateTimeField(auto_now=True)
	my_date_field		= models.DateField(auto_now=False, auto_now_add=False)
	slug  				= models.SlugField(null=True, blank =True)

	def __str__(self):
		return self.OpportunityNumber

	def get_absolute_url(self):
		return reverse('hours:detail',kwargs={'slug': self.slug})


	@property
	def title(self):
		return self.OpportunityNumber


def hl_pre_save_receiver(sender, instance,*args,**kwargs):
	print('saving..')
	print(instance.timestamp)
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

def hl_post_save_receiver(sender, instance,created, *args,**kwargs):
	print('saved..')
	print(instance.timestamp)

pre_save.connect(hl_pre_save_receiver, sender=HoursLocation)
post_save.connect(hl_post_save_receiver, sender=HoursLocation)

src/volunteerz/timesheet/models.py
from django.db import models
from django.conf import settings

from hours.models import HoursLocation

class Task(models.Model):
	owner				= models.ForeignKey(settings.AUTH_USER_MODEL)
	locations			= models.ForeignKey(HoursLocation)

	taskname   			= models.CharField(max_length =120)
	taskdetail         	= models.TextField (blank=True, null=True)
	public				= models.BooleanField(default =True)
	timestamp    		= models.DateTimeField(auto_now_add =True)
	updated	     		= models.DateTimeField(auto_now=True)

	class Meta:
		ordering= ('-timestamp', '-updated')

src/volunteerz/hours/forms.py
from django import forms
from .models import HoursLocation

class DateInput(forms.DateInput):
    input_type = 'date'

class HoursCreateForm(forms.Form):
	OpportunityNumber   = forms.CharField(required=False)
	ChildsName         	= forms.CharField(required=False)
	location     		= forms.CharField(required=False)
	hours        		= forms.CharField(required=False)
	my_date_field		= forms.DateField(required=False)

class HoursLocationCreateForm(forms.ModelForm):
	class Meta: 
		model = HoursLocation
		fields =[
				'OpportunityNumber',
				'ChildsName',
				'location',
				'my_date_field',
				'hours',
				# 'owner'

		]

src/volunteerz/hours/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import random
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render , get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, FormView
# Create your views here.
#function based view
from .forms import HoursCreateForm, HoursLocationCreateForm
from .models import HoursLocation

# 

class HoursListView(ListView):
    def get_queryset(self):
        slug=self.kwargs.get("slug")
        if slug:
                queryset=HoursLocation.objects.filter(
                    Q(OpportunityNumber__iexact=slug)
                    )
        else:
            queryset=HoursLocation.objects.all()
        return queryset


class HoursDetailView(DetailView):
    queryset=HoursLocation.objects.all()

class HoursLocationCreateView(LoginRequiredMixin,CreateView):
    template_name = 'hours/addform.html'
    login_url='/login/'
    form_class = HoursLocationCreateForm
   

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(HoursLocationCreateView, self).form_valid(form)



        

        #@login_required(login_url='/login/')
# def HoursCreateView(request):
#     form = HoursLocationCreateForm(request.POST or None)
#     if form.is_valid():
#         if request.user.is_authenticated():
#             instance=form.save(commit=False)
#             instance.owner = request.user
#             instance.save()
#             return HttpResponseRedirect("/hours/")
#     if form.errors:
#         print(form.errors)

#     template_name ='hours/addform.html'
#     context = {"form": form}
#     return render(request, template_name, context)



# def HoursListView(request):
#     template_name ='hours/hourslist.html'
#     queryset = HoursLocation.objects.all()
#     context ={
#         "object_list": queryset
#     }
#     return render(request,template_name, context)

src/volunteerz/timesheet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render , get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
# Create your views here.
#function based view
from .forms import TaskCreateForm
from .models import Task

# 

class TaskListView(ListView):
    def get_queryset(self):
        slug=self.kwargs.get("slug")
        if slug:
                queryset=Task.objects.filter(
                    Q(OpportunityNumber__iexact=slug)
                    )
        else:
            queryset=Task.objects.all()
        return queryset


class TaskDetailView(DetailView):
    queryset=Task.objects.all()

class TaskCreateView(LoginRequiredMixin,CreateView):
    template_name = 'task/addform.html'
    login_url='/login/'
    form_class = TaskCreateForm
   

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(TaskCreateView, self).form_valid(form)



        

        #@login_required(login_url='/login/')
# def HoursCreateView(request):
#     form = HoursLocationCreateForm(request.POST or None)
#     if form.is_valid():
#         if request.user.is_authenticated():
#             instance=form.save(commit=False)
#             instance.owner = request.user
#             instance.save()
#             return HttpResponseRedirect("/hours/")
#     if form.errors:
#         print(form.errors)

#     template_name ='hours/addform.html'
#     context = {"form": form}
#     return render(request, template_name, context)



# def HoursListView(request):
#     template_name ='hours/hourslist.html'
#     queryset = HoursLocation.objects.all()
#     context ={
#         "object_list": queryset
#     }
#     return render(request,template_name, context)

src/volunteerz/templates/about.html
{% extends "base.html"  %}
	{% block head_title %} About || {{block.super}} {% endblock head_title %}
{% block content %}
		<h1> About Us </h1>
		{% include 'snippets/sidebar.html' %}
{% endblock %}

src/volunteerz/templates/base.html
<!DOCTYPE html>	
	<html lang=en>

		<head>
		<title>{% block head_title %} Volunteerz.com{% endblock head_title %}</title>
		{% include 'snippets/css.html'%}
		</head>
		<body>
		<h1>Hours </h1>
		{% include 'snippets/navbar.html'%}
	<div class ='container'>
		{%block content %} 
		{% endblock content %}
	</div>
	{% include 'snippets/js.html'%}
	</body>
</html>

src/volunteerz/templates/contact.html
{% extends "base.html"  %}
	{% block head_title %} Contact || {{block.super}} {% endblock head_title %}
{% block content %}
		<h1> Contact </h1>
{% endblock %}

src/volunteerz/templates/home.html
	{% extends "base.html" %}	
	{% block head_title %} Welcome || {{block.super}} {% endblock head_title %}
	{%block content %}
	{{block.super}}
		<h1>Volunteerz.com</h1>
		<h1> Hello World </h1>
		<p> 
			This is  {{html_var}} Text
		</p>
		<p>
		{% if bool_item %}
		Number {{num}}
		{% endif %}
		</p>
		<p> {% for some_item in some_list %}
		
		{% if some_item|divisibleby:"2" %}

			Even Numebr
		{% endif %}

				{{some_item}} </br>
			{% endfor %} 
</p>
<p>{{some_item}}
</p>
{% endblock content %}

src/volunteerz/templates/hours/addform.html
{% extends "base.html" %}

{% block head_title %} Add Hours || {{block.super}}{% endblock head_title %}

{% block content %}

{{request.user}}
<h1>Add Hours</h1>
<h1>
	<form method="POST"> {% csrf_token %}
	{{form.as_p}}
	<button type='submit'>Save</button>
	</form>
</h1>

{% endblock %}

src/volunteerz/templates/hours/hourslist.html
{% extends "base.html" %}

{% block head_title %} Hours || {{block.super}}{% endblock head_title %}

{% block content %}
<h1>Hours</h1>

<ul>
{% for obj in object_list %}	
	<li>{{ obj.name }} {{ obj.location }} {{ obj.hours }} {{ obj.timestamp }} {{ obj.my_date_field }}</li>
{% endfor %}

</ul>
{% endblock %}

src/volunteerz/templates/hours/hourslocation_detail.html
{% extends "base.html" %}

{% block head_title %} Hours || {{block.super}}{% endblock head_title %}

{% block content %}
<h1>Hours Details</h1>
<h1>
{{object.title}}
{{object.OpportunityNumber}}
<p>{{object.ChildsName}}</p>
<p>{{object.location}}</p>
<p>{{object.my_date_field}}</p>
<p>{{object.timestamp}}</p>
<p>last updated {{object.updated|timesince}}</p>
</h1>

{% endblock %}

src/volunteerz/templates/hours/hourslocation_list.html
{% extends "base.html" %}

{% block head_title %} Hours || {{block.super}}{% endblock head_title %}

{% block content %}
<h1>Hours</h1>

<ul>
{% for obj in object_list %}	
	<li>
	<a href='{{ obj.get_absolute_url }}'> {{ obj.location }} </a>

  {{ obj.hours }} {{ obj.timestamp }} {{ obj.my_date_field }} <br>
 </li>
{% endfor %}

</ul>
{% endblock %}

src/volunteerz/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

src/volunteerz/templates/snippets/js.html
<script   src="https://code.jquery.com/jquery-3.2.1.min.js"   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="   crossorigin="anonymous"></script>  

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

src/volunteerz/templates/snippets/navbar.html
<div class="container">
<a href='{% url "home" %}'> Home </a> <br>
<a href='{% url "about" %}'> About</a><br>
<a href='{% url "hours:create" %}'> Add Hours</a> <br>
<a href='{% url "hours:list" %}'> View Hours</a> <br>
</div>

src/volunteerz/templates/snippets/sidebar.html
<ul>
<li> Item 2 </li>
<li> Item 3</li>
</ul>